# Generated by Django 5.0.7 on 2024-08-11 01:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("event", "0003_alter_registrationmodel_ticket"),
    ]

    operations = [
        migrations.AddField(
            model_name="registrationmodel",
            name="booked_tickets",
            field=models.IntegerField(default=0),
        ),
    ]
